version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR Public (CLI v1 compatible)...
      - $(aws ecr-public get-login --no-include-email --region us-east-1)
      - REPOSITORY_URI=public.ecr.aws/t7x1c6c1/docker-demo-app
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR Public...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '{"ImageURI":"%s"}' "$REPOSITORY_URI:$IMAGE_TAG" > imageDetail.json

artifacts:
  files:
    - imageDetail.json
